include user.cfg
-include esp82xx/common.mf
-include esp82xx/main.mf

ifndef TARGET
# Fetch submodule if the user forgot to clone with `--recursive`
GETSUBMODS = all burn burnweb netweb netburn clean cleanall purge
.PHONY : $(GETSUBMODS)
$(GETSUBMODS) :
    $(warning Submodule esp82xx was not fetched. Trying it now.)
    git submodule update --init --recursive
    $(info Re-unning make...)
    make $@ $(MFLAGS) $(MAKEOVERRIDES)
endif

# Example for a custom rule.
# Most of the build is handled in main.mf
.PHONY : showvars
showvars:
	$(foreach v, $(.VARIABLES), $(info $(v) = $($(v))))
	true

